name: Automating ASAM Dashboard
run-name: ASAM Dashboard Update
on: 
    schedule:
         #run everyday at noon
        - cron: "0 0 * * ?"
    workflow_dispatch:
jobs:
    build_app:
        runs-on: ubuntu-latest
        name: Run end-of-week Datapane apps
        steps:        
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - uses: py-actions/py-dependency-install@v4
              with: 
                path: requirements.txt
            - uses: datapane/build-action@v2
              with:
                  script: "dashboard.py"
                  token: ${{ secrets.datapane }}
